"""empty message

Revision ID: ea81db995e62
Revises: fc755468843f
Create Date: 2019-03-21 16:14:41.502744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea81db995e62'
down_revision = 'fc755468843f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isActive', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isActive')
    # ### end Alembic commands ###
