"""empty message

Revision ID: fc755468843f
Revises: 1dd4144640e8
Create Date: 2019-03-21 16:01:19.913979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc755468843f'
down_revision = '1dd4144640e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('utype', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'utype')
    # ### end Alembic commands ###
